name : Application deployment on AWS
on:
  Workflow_call
  
jobs:
  working-job:
    runs-on: ubuntu-latest

    steps:
      - name: Echo Message
        run: echo "Application deployment on AWS successfully ✅"